### ISSUE TITLE
Using a git resource for files

### ISSUE THREAD

**Issue by marcusorjames** [18F/s3-resource-simple#28]
I might be missing something basic here as I am quite new to concourse, but I am trying to upload the contents of a git repo to S3...with some exclusions. It seems that when providing the git repo as in input to the s3 resource it always uploads to the repo name. I imagine because it is cloning into that as a folder, which then gets synced up:

```
---
resource_types:
  - name: s3-put
    type: docker-image
    source:
      repository: 18fgsa/s3-resource-simple
resources:
  - name: site
    type: git 
    source:
      uri: ssh://***/site.git
      branch: master
      private_key: ((git-private-key))
  - name: my-s3-bucket
    type: s3-put
    source:
      access_key_id: ((aws-access-key-id))
      secret_access_key: ((aws-secret-access-key)) 
      bucket: my-s3-bucket
      options:
        - "--exclude '*'"
        - "--include 'site/*'" #only this seems to work
      region: eu-west-1
jobs:
  - name: deploy
    serial: true
    plan:
      - get: holding-site
      - put: my-s3-bucket
```

Ideally I would want it to sync into the root of the bucket.

Thanks in advance for any help
